spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: LOGIN-SERVICE
server:
  port: 8767
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true
---
spring:
  profiles: test
  application:
    name: LOGIN-SERVICE-TEST
server:
  port: 8768
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true
